### ISSUE TITLE
add thumbnail generation module

### ISSUE THREAD

**Issue by dyf** [AllenInstitute/ipfx#134]
Found a forgotten module in the old repository that didn't survive the migration to IPFX:

http://stash.corp.alleninstitute.org/projects/INF/repos/lims2_modules/browse/mousecelltypes/ephys/thumbnail/create_ephys_thumbnails.py

I propose that we migrate what we need out of here into a new ArgSchema-fied `run_create_thumbnails.py` module in /bin.

**Comment by wbwakeman** [comment]
See also http://jira.corp.alleninstitute.org/browse/PBS-1132

**Comment by wbwakeman** [comment]
Closing in favor of ipfx #467
