### ISSUE TITLE
python 2 compatibility? (f-strings)

### ISSUE THREAD

**Issue by tmchartrand** [AllenInstitute/ipfx#168]
If this is intended to be fully python 2 compatible, there are several cases of f-string usage that will need to be replaced. The ones I encountered are in nwb_to_pdf, but it looks like there are several in x_to_nwb also.

**Comment by dyf** [comment]
Everything but the `x_to_nwb` converters are py2-only.  Those converters are py3-only.  We'll be migrating everything to py3-only over the next few months.

**Comment by tmchartrand** [comment]
Cool thanks, good to know!

**Comment by t-b** [comment]
@tmchartrand `x_to_nwb` needs at least python 3.6 due to the f-strings.

**Comment by t-b** [comment]
Closing in favour of #141.
