### ISSUE TITLE
Negative amplitude of test pulse on voltage clamps

### ISSUE THREAD

**Issue by sgratiy** [AllenInstitute/ipfx#229]
Negative pulse breaks `measure_initial_access_resistance` function
E.g.: /allen/programs/celltypes/production/mousecelltypes/prod732/Ephys_Roi_Result_757308882/Cck-IRES-Cre;Vip-IRES-FlpO;Ai65-415022.05.01.04.nwb

![test_pulse_negative_voltage_clamps](https://user-images.githubusercontent.com/38869851/58666830-4bab0200-82e9-11e9-8f74-f6c436db1e23.png)

**Comment by sgratiy** [comment]
@bergjim, @timjarsky  Should we allow negative test pulse on Voltage Clamps as shown in the figure attached to the issue? Why do test pulses sometimes have negative amplitude?

**Comment by bergjim** [comment]
@sgratiy Sometimes the test pulse is run negative in current clamp and the user forgets to change the setting for the next experiment. We should actually not even have TP inserted into those pulses - you can ignore the first square and calculate resistance values from the other three.

**Comment by sgratiy** [comment]
@bergjim thanks for the explanation. Will do.
