### ISSUE TITLE
Some Long Squares miss Test Pulse

### ISSUE THREAD

**Issue by sgratiy** [AllenInstitute/ipfx#230]
@bergjim @timjarsky 
Occasionally, Current Clamp sweeps miss Test pulse as shown in the figure below.
What should we do with these sweeps? Currently these sweeps are being failed, which often causes the feature extractor to fail as well.
![no_test_pulse_long_squares](https://user-images.githubusercontent.com/38869851/58726982-fb3ead80-8397-11e9-997d-378ff1be67d5.png)

**Comment by bergjim** [comment]
@sgratiy - These sweeps should fail. I'll work with Tim to require TP_insert in the future

**Comment by sgratiy** [comment]
Currently these sweeps are failed as 'Stimulus pulse is missing'. Need to change to something like:
"Improper stimulus"
