### ISSUE TITLE
Test run ephys pipeline with nwb2 files

### ISSUE THREAD

**Issue by sgratiy** [AllenInstitute/ipfx#251]
- [x] able convert abf 
- [x] able to convert dat files to nwb2
- [x] get nwb2 and corresponding nwb1 files from Jim
- [x] test  run pipeline locally with MIES nwb files

**Comment by wbwakeman** [comment]
ABF to NWB2 (works on Windows, not Linux): report to PyABF project
DAT to NWB2 (need ontology: JimB)
NWB2 (get from JimB)

Need NWB1 file (either generate from MIES) or write converter

**Comment by sgratiy** [comment]
Created an issue on pyabf project
https://github.com/swharden/pyABF/issues/81

**Comment by wbwakeman** [comment]
As of January 14, 2020, we have received a new set of files generated from our MIES systems.  Need to run through feature extractor and confirm that features and are correct.

**Comment by wbwakeman** [comment]
Run that test set from MIES through ipfx; smoke test results; prepare feedback for hackathon.

**Comment by sgratiy** [comment]
Installed MIES on a windows machine to test conversion of pxp to nwb1/nwb2. Found that the MIES has a bug when converting pxp to nwb2.
Ran pipeline with nwb1 and nwb2 both converted from the same MIES generated pxp experiments.
The pipeline_output json has some differences in metadata but the features extracted are identical for the 3 files tested.

Created issue to address differences of metadata read from nwb1 vs nwb2:
https://github.com/AllenInstitute/ipfx/issues/321
