### ISSUE TITLE
Questions converting external ABFv2 files to NWBv2 using run_x_to_nwb_conversion

### ISSUE THREAD

**Issue by youngseok-seo** [AllenInstitute/ipfx#261]
Hi @t-b ,

We've tried converting ABFv2 files from two external collaborating labs to NWBv2 using the function run_x_to_nwb_conversion.py in the repo. 

Our attempts to convert each file return slightly different errors (see screenshots below), likely resulting from pyabf or pynwb (not ipfx). Advice or guidance is appreciated.

Thanks,
@youngseok-seo and @stripathy 

File locations:
ABFv2 file 1: https://github.com/youngseok-seo/NWB/blob/master/data/18823040.abf
ABFv2 file 2: https://github.com/youngseok-seo/NWB/blob/master/data/JS-A2-C03(350)-P01-2017_10_13_0013.abf

![image](https://user-images.githubusercontent.com/46095808/61901641-379d0e80-aeee-11e9-9da2-68152165b2d4.png)

![image](https://user-images.githubusercontent.com/46095808/61901694-54d1dd00-aeee-11e9-91bc-2c5d2ac2c9aa.png)

**Comment by bendichter** [comment]
@youngseok-seo `ValueError: **** already exists in 'root'` is an error that generally occurs when you try to add two objects of the exact same name. Here, it looks like the f-formatted string is not being unpacked, i.e. you are attempting to add an object named `Electrode {x:d}` (at least) twice. f-strings are only supported in python 3, so I think this might be a py2/py3 issue.

**Comment by t-b** [comment]
ipfx only supports python 3.6, btw.

**Comment by sgratiy** [comment]
@youngseok-seo have you issue been resolved?

**Comment by t-b** [comment]
@youngseok-seo I could convert both files successfully. Can you recheck? And also check if you are using python 3.6 or later via `python --version`.

**Comment by wbwakeman** [comment]
No response. Closing
