### ISSUE TITLE
Update "EPHYS_NWB_CONVERTER_QUEUE" to use py3

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ipfx#268]
The module used by the "EPHYS_NWB_CONVERTER_QUEUE" needs to be updated to use Py3.

Then the LIMS executables path needs to be updated to use the updated module.

/shared/bioapps/infoapps/lims2_modules/lib/allensdk/allensdk/internal/pipeline_modules/IVSCC/ephys_nwb/convert_igor_nwb.py

**Comment by sgratiy** [comment]
@wbwakeman I am curious, where did you get the above path for the module?
When I look on LIMS for the executable of this queue. I see the path:
/allen/aibs/technology/conda/production/tc_stitch_legacy_27/lib/python2.7/site-packages/allensdk/internal/pipeline_modules/IVSCC/ephys_nwb/convert_igor_nwb.py

**Comment by sgratiy** [comment]
My understanding is that we want to try to drop this queue if we can, correct? Only if we cannot, then we would try to update the module to py3. 
Thus, I have updated the transitions to skip this queue. Let's see what happens downstream....

**Comment by wbwakeman** [comment]
While it was broken, I tried to run it using a Py27 environment that Nile created.  That is the tc_stitch_legacy_27 environment that you see.  The path in the description is the original program that was running before it broke last week.

Thanks for changing the job_transition in LIMS.  Yes, we will drop this conversion if we can.

**Comment by wbwakeman** [comment]
After discussions with Jim Berg, we agreed that we no longer need this step (since ephys experiment from now will be the Patch-seq type).  Therefore, Sergey just changed the LIMS2 job_transition to circumvent this step.
