### ISSUE TITLE
Extend allensdk_anaconda3 docker image to include hdf5

### ISSUE THREAD

**Issue by sgratiy** [AllenInstitute/ipfx#273]
nwb2 conversion tests require h5diff executable. The existing docker image used for testing does not have h5diff installed.

**Comment by gouwens** [comment]
Related to this, if a user (like myself, for example) doesn't have the h5diff executable installed, some of those the `test_nwb1_nwb2_conversion.py`tests fail. I'm not sure if there's a way signifying to the user to include that (some kind of requirements file?). Or maybe skip the test if the executable isn't present?

**Comment by t-b** [comment]
@gouwens Something like https://github.com/AllenInstitute/ipfx/blob/74904808979dab54125df23de0d0e27aceba9207/tests/test_x_nwb.py#L56 can to the trick.

**Comment by wbwakeman** [comment]
No longer needed, since we are no longer pursuing the conversion of nwb1 to nwb2 in an ipfx function
