### ISSUE TITLE
Resolve add_child deprecated warning in test

### ISSUE THREAD

**Issue by sgratiy** [AllenInstitute/ipfx#276]
When running as test getting a deprecation warning:
`add_child is deprecated. Set the parent attribute instead.`

When running as a script do not get the warning

```
import os
import pytest
from ipfx.x_to_nwb.NWBConverter import NWBConverter
from ipfx.bin.run_nwb1_to_nwb2_conversion import make_nwb2_file_name


@pytest.mark.parametrize('NWB_file_inhouse', ['/local1/ephys/nwb_debug/single.nwb'])
def test_file_level_regressions(NWB_file_inhouse):

    nwb1_file_name = NWB_file_inhouse
    base_name = os.path.basename(nwb1_file_name)

    test_dir = os.path.dirname(nwb1_file_name)

    tmpdir = "/local1/ephys/nwb_debug"
    temp_nwb2_file_name = make_nwb2_file_name(tmpdir,base_name)


    NWBConverter(input_file=nwb1_file_name,
                     output_file=temp_nwb2_file_name,
                     )


# if __name__=="__main__":
#
#     test_file_level_regressions("/local1/ephys/nwb_debug/H18.03.315.11.11.01.05.nwb")

```

Action  plan:
- [x] hide warning with pytest.ini
- [x] report issue to pynwb https://github.com/NeurodataWithoutBorders/pynwb/issues/1099

**Comment by wbwakeman** [comment]
Causes extensive clutter in test files.
Correct solution is for HDMF project to update this.
Since we are pinned to a version, this will break the test when we try an updated version.
Check that it has not been resolved, then alert PyNWB project
suppress the warning
