### ISSUE TITLE
Refactor nwb_reader

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ipfx#286]
Refactor nwb_reader to be based on version of nwb rather than mix of nwb version and the pipeline version.
Currently there are 3 nwb reader classes:
NwbXreader for reading nwb2 files
NwbPipelineReader for reading nwb1 files produced by pipeline
NwbMiesReader for reading Mies generated nwb file

These support AibsDataSet(nwb1) and HBGDataSet (nwb2) objects
The relationship between DataSet classes and nwb reader classes is not confusing. As we are moving to nwb2, AibsDataSet should support nwb2 files as well.

Need design DataSet classes and readers such to support MIES or non MIES nwb both for nwb1 and nwb2 plus give some consideration for different version of nwb1/pipeline
-------------------
Completed:
Designed refactor
Refactored all classes

Remaining:
integrate individual components and ensure tests run successfully (8) (resolve any problems that arise)
write additional tests for new classes (HBGNWBData, MIESNWEBData, EphysDataSetClass) (5)
Deprecate older classes, functionality and tests (5)

**Comment by sgratiy** [comment]
Existing architecture of nwb reader and dataset is here
http://confluence.corp.alleninstitute.org/display/PP/Publishing+IVSCC+NWB2+publish+module%2C+v3
