### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by tmchartrand** [AllenInstitute/ipfx#293]
I just noticed that many of the examples in the docs/gallery don't run currently, seems like they didn't get updated when some of the code was refactored (e.g. references to `ipfx.ephys_extractor` which is now `ipfx.feature_extractor` I believe).
Would be great to update the examples and related documentation.

**Comment by wbwakeman** [comment]
Fixed by #384 ?

**Comment by tmchartrand** [comment]
looks like it, thanks guys!
