### ISSUE TITLE
Wireframe Sweep QC tool

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ipfx#296]
Wireframe the layout of a Sweep QC tool.  Document on this page:
http://confluence.corp.alleninstitute.org/display/PP/Sweep+QC+Tool

Provide name, description, axes labels and units for plots and a sensible description for each value or plot.
Provide names for groupings of plots.

**Comment by sgratiy** [comment]
I have updated the Sweep QC tool with the proposed design.
