### ISSUE TITLE
Set up minimal deployment for sweep QC tool

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ipfx#299]
Set up deployment environment for a minimal Sweep QC tool.

Consider how we will deploy the tool to ephys rigs at the Institute and make it available for external users to get the tool for their use.

**Comment by NileGraddis** [comment]
repo here:
https://github.com/AllenInstitute/sweep_qc_tool

Also see releases on that repo. Every time a tag of format vX.Y.Z is pushed to to a commit on master, appveyor promotes that tag to a github release and publishes a packaged windows binary to the release.
