### ISSUE TITLE
Returning NaNs in response breaks feature extraction

### ISSUE THREAD

**Issue by gouwens** [AllenInstitute/ipfx#305]
The switch to returning NaNs in the response vector (instead of zeros, I believe) currently breaks feature extraction for cells to which this applies.

The first issue I tracked down is that the filtering fails in https://github.com/AllenInstitute/ipfx/blob/b77da8b2cac12ee62585b2016c40e360cc6ec395/ipfx/time_series_utils.py#L24. If there are NaNs, it just returns an empty array.

I don't know if other things are broken.

One internal specimen ID for which this breaks is 913901697.

I think there needs to be a test for this (or should have been identified before this change went into master?).

**Comment by gouwens** [comment]
I think one solution may be to mask out the NaNs at the point of Sweep object creation (it seemed to work for processing the specimen I mentioned above), but I'm not sure if there'd be other consequences from that.

**Comment by tmchartrand** [comment]
Seems like the proper fix to this might be to let the sweep keep the full data with NaNs, but change the default epoch from sweep to recording, which is just the masked data (most of the fx code selects the recording epoch anyway, so those calls could be trimmed). The effect would be essentially the same, but the full sweep would be there in case anyone needs it.

**Comment by sgratiy** [comment]
Indeed, as @tmchartrand the tests pass if we select "recording" epochs in the sweeps before passing them to the sweep extractor. @gouwens how did you run the feature extractor for the specimen  913901697? What kind of error did you get?

**Comment by sgratiy** [comment]
@gouwens Do you believe we resolved this issue following fixings tests and merging chrip branch into master?

**Comment by gouwens** [comment]
@sgratiy I'll check cells I had an issue with previously.

**Comment by gouwens** [comment]
@sgratiy The cells I tested work, so I think we can close this issue.
