### ISSUE TITLE
Please could you update Readme file with guidelines

### ISSUE THREAD

**Issue by sarmishta** [AllenInstitute/ipfx#309]
Hi, I have been trying to run this package to extract data from https://celltypes.brain-map.org/experiment/electrophysiology/528706755. But, in the process encounter errors like ontology file not found, h5py OSError and so on. Please could you update the guidelines in the readme file on how to use the package? Thank you!

**Comment by wbwakeman** [comment]
Hi @sarmishta 

Could you please paste in the command(s) that you are running, and the output that you get?

Thanks,
Wayne

**Comment by tmchartrand** [comment]
@sarmishta I would also note that for now you may be better served by using the older and more stable tools in AllenSDK (https://github.com/AllenInstitute/AllenSDK), unless there's a specific functionality new to IPFX that you were looking for.
See the tutorial here for more info: https://allensdk.readthedocs.io/en/latest/_static/examples/nb/cell_types.html#Computing-Electrophysiology-Features

**Comment by sarmishta** [comment]
@wbwakeman 

Firstly I used,
$ cd ipfx/ipfx/bin
 $ python pipeline_from_nwb.py input_nwb_file

And had to change a few import statements and install ipfx using the installation.rst provided in the docs folder,
$ pip install ipfx/
Then it wasn't picking up the default ontology file, so moved it from defaults folder to the output folder created. 

Now, I get the following error,

INFO:root:
INFO:root:***** ***** ***** Extract QC features ***** ***** *****
INFO:root:=======================================================
INFO:root:
Traceback (most recent call last):
  File "pipeline_from_nwb_file.py", line 55, in <module>
    if __name__ == "__main__": main()
  File "pipeline_from_nwb_file.py", line 51, in main
    pipe_input["manual_sweep_states"])
  File "/Users/sarmishta/Desktop/MS/ipfx/ipfx/bin/run_pipeline.py", line 25, in run_pipeline
    stimulus_ontology_file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipfx/bin/run_sweep_extraction.py", line 49, in run_sweep_extraction
    ontology=ont)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipfx/data_set_utils.py", line 21, in create_data_set
    nwb_version = get_nwb_version(nwb_file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipfx/nwb_reader.py", line 628, in get_nwb_version
    with h5py.File(nwb_file, 'r') as f:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

Is there a specific python version to be used? I am currently using Python 3.7
Any inputs and help would be appreciated! Thank you.

**Comment by sarmishta** [comment]
@tmchartrand I was wondering if the Electrophysiology Features computed from the AllenSDK would be different from the ones computed from ipfx.

**Comment by tmchartrand** [comment]
@sarmishta the primary feature set available should be the same in both I believe (possibly minor implementation differences, but nothing too consequential). The main purpose of splitting off this package was to accommodate a wider range of file types, but for now any files accessed through our website or through AllenSDK are fully compatible with the AllenSDK feature extraction. 
There are some additional undocumented features available in IPFX too (and will likely be more in the future), but that code is not really intended for widespread use at this point.

**Comment by gnayuy** [comment]
@sarmishta ipfx prefers python 3.6. Please see the guidelines I summarized in below:

1. create a clean environment with conda (if you've already done this, please ignore) with "conda create -n myenv python=3.6" and then "conda activate myenv"

2. install ipfx from [pypi](https://pypi.org/project/IPFX/) with "pip install ipfx"

3. download test datasets with dandi "pip install dandi" and "dandi download https://dandiarchive.org/dandiset/000020". This mouse data is about 114 GB.

4. pick one dataset, e.g. sub-599387254_ses-601506492_icephys.nwb from mouse data, create output directory for saving the results, e.g. "mkdir outputs" and "mkdir outputs/qc", then run " python -m ipfx.bin.run_pipeline_from_nwb_file sub-599387254_ses-601506492_icephys.nwb outputs --qc_fig_dir outputs/qc" to extract features.

The extract features will be saved into outputs/sub-599387254_ses-601506492_icephys/output_json. The figures can be found in outputs/qc. Hope this helps.
