### ISSUE TITLE
plan inputs and outputs for icephys nwb2

### ISSUE THREAD

**Issue by NileGraddis** [AllenInstitute/ipfx#312]
goal: come up with a detailed set of issues describing the work that needs to be done in order for ipfx to support nwb2.

- [x] In preparation for NWB Hackathon project Review and refine ICEphys Metadata extension,
- [x] define the data that we want to have in an NWB2 file
- [x] define the expected scope of work.

So that we can lead that project to guide us on how to create these files, so that we can do it once.

**Comment by sgratiy** [comment]
Defined data that we want to have in the NWB2 file based on the analysis of the existing nwb1 implementation:
http://confluence.corp.alleninstitute.org/display/PP/Publishing+ephys+NWB2+files

**Comment by wbwakeman** [comment]
Could not get consensus on what should be in the file and what should be available from another resource (e.g. BCDC).  Session level metadata will only include (cell) specimen id for now.
Sweep-level metadata to include:
stimulus_name
stimulus_interval
stimulus_amplitude
stimulus_type_name
stimulus_unit
#316
#323
