### ISSUE TITLE
scope nwb 1->2 conversion work

### ISSUE THREAD

**Issue by NileGraddis** [AllenInstitute/ipfx#313]
goal: Determine the tasks that need to be completed in order to convert nwb 1 files to nwb 2. This will involve answering the questions posed in #310

**Comment by wbwakeman** [comment]
Most likely solution will rely on processing old .pxp files with updated MIES to produce NWB2 files, then running ipfx feature extraction.  

May require an update to "NWB publish" code to add required metadata: https://github.com/AllenInstitute/AllenSDK/issues/1279

Need to understand all of DANDI archive requirements for NWB2 files also
