### ISSUE TITLE
Update nwb publish code

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ipfx#316]
The code to create publishable NWB files for the June data release needs an update.  
http://confluence.corp.alleninstitute.org/display/IT/IVSCC+NWB+publish+module%2C+v2

The extent of the issue is described on page:
http://confluence.corp.alleninstitute.org/display/PP/Publishing+IVSCC+NWB2+publish+module%2C+v3

Need to create a new well known file type to associate these records with.  Current ones use 'NWBDownload'.  Need something different so that we can still have 'NWBDownload' for the Cell Types app and also make the new NWB2 files available.  'NWB2Download'??

File name must contain cell_specimen.id 

Find required metadata so that we can write it into the new file.
Building the scaffold for doing this work
LIMS update to make sure we are getting the required inputs, and writing the correct output (the new well known file record)

Metadata document:
https://docs.google.com/document/d/1KaQTtZ1AWSjHQsC3XO4k3BT5Z_pjVb4F6fIzrTEClhs/edit#heading=h.diqkrf5s0jti

----------------------
Completed:
spec what to do
Implement the python module that does this
LIMS strategy update (PR is open; awaiting review)

Todo:
follow-up on responses from NWB group
 - missing resistance value
 - PyNWB cannot read, then write; container_source private attribute

**Comment by NileGraddis** [comment]
jira ticket for lims side is PBS-2161

**Comment by wbwakeman** [comment]
remaining lims work tracked in new issue
