### ISSUE TITLE
Merge functionality from scientists into master

### ISSUE THREAD

**Issue by sgratiy** [AllenInstitute/ipfx#318]
- [x] Fix test error and merge chirp analysis (https://github.com/AllenInstitute/ipfx/pull/283)

- [ ] Fix test errors and merge Tom's improvements that helped salvage several cells in the pipeline https://github.com/AllenInstitute/ipfx/pull/324
 - [x] Fix test errors and merge https://github.com/AllenInstitute/ipfx/pull/325

**Comment by sgratiy** [comment]
@tmchartrand could you please create a PR to integrate your changes into master? This would add a necessary visibility to the task. I merged Nathan's chirp into master which is passing all the tests. To avoid PR conflicts, could you possibly merge origin/master into your branch or rebase, and please re run the tests again. To run all the tests please use:
TEST_INHOUSE=true pytest <test folder>
that would run tests depending on test data that is only available in house.
Let me know of any issues concerns.

**Comment by NileGraddis** [comment]
I'm looking at #324
