### ISSUE TITLE
Host ipfx on pypi

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ipfx#326]
and make it pip-installable

also to address #279

**Comment by gnayuy** [comment]
the deployment of IPFX works on the master branch (https://pypi.org/project/ipfx/)

**Comment by gnayuy** [comment]
new version v1.0.0.beta5 is on pypi https://pypi.org/project/IPFX/ (the links to quick_start, tutorial, and contribution guide in readme/project description are updated for clickable on pypi)
