### ISSUE TITLE
circleci failing on installing pyabf

### ISSUE THREAD

**Issue by tmchartrand** [AllenInstitute/ipfx#328]
Currently tests are failing due to an installation issue, so there is no useful feedback on PRs. Perhaps we could prioritize this fix ASAP?

**Comment by NileGraddis** [comment]
This is addressed (temporarily) by #329. When [this pr](https://github.com/swharden/pyABF/pull/104) or equivalent functionality is implemented in pyABF we can stop installing from my fork.
