### ISSUE TITLE
productionize #324

### ISSUE THREAD

**Issue by NileGraddis** [AllenInstitute/ipfx#330]
[this pr](https://github.com/AllenInstitute/ipfx/pull/324) adds an important new feature: partial feature extraction runs. In order to merge it, we need to:
1. add unit tests
2. add documentation
3. carry out some light refactoring (see review comments)
4. resolve the integration test failures mentioned in the pr

**Comment by wbwakeman** [comment]
This should be addressed by PR #449 which has been merged into the released version of ipfx.  Now available from pypi: `pip install --upgrade ipfx`

Please use that updated version and let us know if there are still issues that need to be addressed.
