### ISSUE TITLE
Extend ABFConverter.py to not require mcc settings file

### ISSUE THREAD

**Issue by youngseok-seo** [AllenInstitute/ipfx#341]
The existing ABFConverter script within x_to_nwb requires providing a settings.json file that reflects multiclamp commander amplifier settings. 

As this settings file is typically not available for historical datasets, it would be helpful to modify the ABF conversion script to make this providing of the settings file optional and to set those fields to NA (or some other equivalent).

This issue is related to #261

**Comment by t-b** [comment]
This is fixed in https://github.com/byte-physics/x-to-nwb.
