### ISSUE TITLE
Extend ABFConverter to accept user-defined channel names

### ISSUE THREAD

**Issue by youngseok-seo** [AllenInstitute/ipfx#342]
The current ABFConverter script uses a hard-coded list of expected channel names: 
https://github.com/AllenInstitute/ipfx/blob/74904808979dab54125df23de0d0e27aceba9207/ipfx/x_to_nwb/ABFConverter.py#L31

We need to extend this to meet two additional use cases:

- Occasionally, user defined channel names are used. 
- Occasionally, in some two-electrode set ups, one electrode is not used in the experiment but this channel is not explicitly turned off. We need a way to tell the converter about this so that the data from this channel is not added to the resulting NWB file.

**Comment by t-b** [comment]
@youngseok-seo Thanks, I'll tackle that.

**Comment by t-b** [comment]
This is fixed in https://github.com/byte-physics/x-to-nwb.
