### ISSUE TITLE
Run sample dat converted nwb2 through the ipfx and document issues

### ISSUE THREAD

**Issue by sgratiy** [AllenInstitute/ipfx#349]
The sample files are in
\\allen\programs\celltypes\workgroups\279\sample_dat_nwbs

- [x] Document any issues when running feature extraction through the IPFX
- [x] Check which metadata is missing from these files

See comment below for the description of the issues when running these files.
the files in the directory have a pre-test pulse and do no suffer from #269. 

Related to #211, #269

**Comment by wbwakeman** [comment]
Execute run_pipeline executable
mention any errors
run attach_metadata
compare metadata in output NWB file with the list in the ephys metadata google doc

**Comment by sgratiy** [comment]
- All 6 files in the folder /allen/programs/celltypes/workgroups/279/sample_dat_nwbs/ fail QC for a range of reasons:

- All experiments fail sweep qc because pre- and post-noise value exceed qc threshold by factor 2-3. Example: 'pre-noise: 0.274 exceeded qc threshold: 0.070', 'post-noise: 0.196 exceeded qc threshold: 0.070'
- Few experiments are missing the seal sweep with the code 'extpciiatt' that fails cell-level qc
- All experiments are failing "intial and input access resistance" qc

Additionally:
Unit for CurrentClampStimulusSeries 'index_00x' is ignored and will be set to 'amperes' as per NWB 2.1.0.
Could not find stimulus: extpexpend - what does it correspond to in ontology?

Below are more specific notes for the individual experiments:
 
H20.28.008.11.05-4.nwb: no seal, failed_input_access_resistance,
H20.28.008.11.05-5.nwb: same as above
H20.28.008.11.05-6.nwb: just failes sweep level qc
H20.28.008.11.05-7.nwb: failed seal, failed intial and input access resistance
H20.28.008.11.05-8.nwb: seal is not available failed initial access resistance
H20.28.008.11.05-10.nwb: failed_input_access_resistance:True

**Comment by sgratiy** [comment]
@wbwakeman because of the problems with these files, attaching metadata is blocked until we can find files that allow us to successfully run feature extractor. Thus, indicated that #356 is blocked by this issue and also move all metadata-related activity to #356. Perhaps we should also bump up the estimate for #356 as well.

**Comment by wbwakeman** [comment]
What is needed to generate NWB files from .dat that can be feature-extracted with ipfx?  Have the person(s) that could help with that been informed about this?  Depending on their response, this ticket may be complete.

It does sound like #356 is blocked.  Perhaps you can move it to the "Blocked" column?

**Comment by bergjim** [comment]
@sgratiy I understand that you can't save a nwb file unless it passes ipfx, but is there any way to know if the metadata is in the right place in the raw nwb file in the first place?

**Comment by sgratiy** [comment]
@bergjim yes we have a hacky way to introspect the nwbs for metadata. I am looking into these files.

**Comment by sgratiy** [comment]
@wbwakeman I put back the point on the issue "Check which metadata is missing from these files" because in #356 it assumes that we can successfully run the pipeline executable. Here we want just to see which metadata the raw nwb files have per Jim's comment. Thus, the issue is not complete yet.

**Comment by NileGraddis** [comment]
@sgratiy I think some of these fields are not currently supported by NWB. For instance, the filter fields I think are currently not modeled - there is just a single string field:
https://github.com/NeurodataWithoutBorders/pynwb/blob/929972d3012aa2664e895ac7231fd0c451cccd6c/src/pynwb/icephys.py#L36

**Comment by sgratiy** [comment]
@NileGraddis yes, I was aware that filtering is just a string field, but this field exists and google doc states, that filtering data should be saved in there. Is that no longer the case?

**Comment by bergjim** [comment]
Thanks @sgratiy @NileGraddis @wbwakeman , this is helpful. I think things are in a good place, but we will probably have some work to do to get the collaborator's data incorporated in the pipeline. I'll have more bandwidth in May and can lead a project to accomplish that - but for now I am fine closing this specific issue.
