### ISSUE TITLE
refactor or replace feature vector integration test

### ISSUE THREAD

**Issue by NileGraddis** [AllenInstitute/ipfx#377]
[this test](https://github.com/AllenInstitute/ipfx/blob/master/tests/test_run_feature_vector.py) queries LIMS for NWB1-formatted data which it then uses as inputs ([see here](https://github.com/AllenInstitute/ipfx/blob/74904808979dab54125df23de0d0e27aceba9207/ipfx/bin/run_feature_vector_extraction.py#L77)). This is hard to run in cloud ci, hard to update, and fragile to external changes (i.e. to lims). This is particularly bad now, since we are moving to NWB2, but this test expects NWB1 files.

We should:

- [x] replace this test with a LIMS-independent test using NWB2 data
- [x] using the new test, carry out any necessary unit-testability-oriented refactoring of the code.
- [x] examine whether unit feature tests cover all the functionality of the run_feature_vector_extraction, run_feature_collection
- [x] implement unit tests

**Comment by gnayuy** [comment]
Refactored the func "data_for_specimen_id" so that "run_feature_vector_extraction" can extract features for local nwb2 files.
The unit test for multiple nwb2 files and test_feature_collection are under refactoring and will be updated soon.

**Comment by sgratiy** [comment]
Re: third bullet point. The test_feature vector has sufficient coverage of the features created by the run_feature_vector. Below is the list of named features and the corresponding tests functions
        "first_ap_v": test_first_ap*
        "first_ap_dv": test_first_ap*
        "isi_shape": test_isi_shape
        "psth": test_psth*
        "inst_freq":  test_inst_freq*
        "spiking_width": "spiking_peak_v", "spiking_fast_trough_v", "spiking_threshold_v", "spiking_upstroke_downstroke_ratio":  test_spike_feature*
        "step_subthresh": test_step_subthreshold, test_step_subthreshold_interpolation
        "subthresh_norm": test_subthresh_norm_normalization
        "subthresh_depol_norm": test_subthresh_depol_norm*,  test_identify_subthreshold_depol_with_amplitudes

All function are covered, thus there appear to be no other need for the unit tests of the feature vector.
