### ISSUE TITLE
update examples to use new EphysDataSet constructor

### ISSUE THREAD

**Issue by NileGraddis** [AllenInstitute/ipfx#379]
This involves: 
- [ ] caching some NWB2 test data in e.g. git lfs (Large File Storage)
- [ ] swapping the examples to use these data
- [ ] making sure the examples look OK

see #372 for more information

**Comment by NileGraddis** [comment]
All of the examples use the same specimen: 595570553, which does not have an NWB2 file yet. It should in the next day or so. Updating the examples is a lot easier if we use the same data (since we can check whether they change!), so I'm moving this to blocked until we have that file.

**Comment by wbwakeman** [comment]
/allen/programs/celltypes/production/humancelltypes/prod181/Ephys_Roi_Result_595570492/nwb2_H17.03.008.11.03.05.nwb

**Comment by NileGraddis** [comment]
So, the examples don't work on master. The problems seem to be mostly import-related. Here they are:

all_analysis
```
Traceback (most recent call last):
  File "docs/gallery/analysis_examples/all_analysis.py", line 29, in <module>
    extract_data_set_features(data_set, subthresh_min_amp=-100.0)
  File "/home/nile/Documents/work/allen_institute/tmp/ipfx/ipfx/data_set_features.py", line 290, in extract_data_set_features
    stimuli=ontology.coarse_long_square_names)
AttributeError: 'NoneType' object has no attribute 'coarse_long_square_names'
```

lsq_analysis, estimate_params
```
Traceback (most recent call last):
  File "docs/gallery/analysis_examples/lsq_analysis.py", line 11, in <module>
    import ipfx.ephys_features as ft
ModuleNotFoundError: No module named 'ipfx.ephys_features'
```

ramp_analysis, short_square_analysis, detect_spikes_single_sweep_window, detect_spikes_single_sweep, spike_train_features
```
Traceback (most recent call last):
  File "docs/gallery/analysis_examples/ramp_analysis.py", line 14, in <module>
    from ipfx.ephys_extractor import SpikeExtractor, SpikeTrainFeatureExtractor
ModuleNotFoundError: No module named 'ipfx.ephys_extractor'
```
sweep_qc
```
Traceback (most recent call last):
  File "docs/gallery/qc_examples/sweep_qc.py", line 28, in <module>
    sweep_features = qcf.sweep_qc_features(data_set)
AttributeError: module 'ipfx.qc_features' has no attribute 'sweep_qc_features'
```
