### ISSUE TITLE
fix gallery examples

### ISSUE THREAD

**Issue by NileGraddis** [AllenInstitute/ipfx#384]
[These are broken](https://github.com/AllenInstitute/ipfx/issues/379#issuecomment-604586966) ([rtd](https://readthedocs.org/projects/ipfx/builds/)), mainly due to refactoring in fe1ad85 & a60fea3 as well as failures to get a default stimulus ontology.

This ticket is to 
- [x] fix these examples

and to ensure that these don't secretly break again by 
- [x] making [readthedocs a pr requirement](https://blog.readthedocs.com/building-docs-for-pull-requests/). EDIT: prs are building, but for some reason statuses aren't being posted back. I don't have a good idea of why this is and have asked their support.

**Comment by NileGraddis** [comment]
imports are fixed, but some issues remain:

ramp_analysis
```
Mean of empty slice
Traceback (most recent call last):
  File "/home/nile/Documents/work/allen_institute/tmp/ipfx/venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'latency'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docs/gallery/analysis_examples/ramp_analysis.py", line 46, in <module>
    sns.rugplot(results["spiking_sweeps"]["latency"].values + start)
  File "/home/nile/Documents/work/allen_institute/tmp/ipfx/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/nile/Documents/work/allen_institute/tmp/ipfx/venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'latency'
```

lsq_analysis
```
Traceback (most recent call last):
  File "docs/gallery/analysis_examples/lsq_analysis.py", line 41, in <module>
    data = lsqa.analyze(lsq_set)
  File "/home/nile/Documents/work/allen_institute/tmp/ipfx/ipfx/stimulus_protocol_analysis.py", line 136, in analyze
    spiking_features = self.analyze_suprathreshold(sweep_set)
  File "/home/nile/Documents/work/allen_institute/tmp/ipfx/ipfx/stimulus_protocol_analysis.py", line 155, in analyze_suprathreshold
    rheobase_sweep_features = self.find_rheobase_sweep(spiking_sweep_features)
  File "/home/nile/Documents/work/allen_institute/tmp/ipfx/ipfx/stimulus_protocol_analysis.py", line 243, in find_rheobase_sweep
    raise ValueError("Cannot find rheobase sweep in spiking sweeps with amplitudes:")
ValueError: Cannot find rheobase sweep in spiking sweeps with amplitudes:
```

all_analysis
```
Mean of empty slice
Traceback (most recent call last):
  File "docs/gallery/analysis_examples/all_analysis.py", line 29, in <module>
    extract_data_set_features(data_set, subthresh_min_amp=-100.0)
  File "/home/nile/Documents/work/allen_institute/tmp/ipfx/ipfx/data_set_features.py", line 318, in extract_data_set_features
    sweep_features = extract_sweep_features(data_set, iclamp_sweeps)
  File "/home/nile/Documents/work/allen_institute/tmp/ipfx/ipfx/data_set_features.py", line 140, in extract_sweep_features
    sweep_set.align_to_start_of_epoch("experiment")
  File "/home/nile/Documents/work/allen_institute/tmp/ipfx/ipfx/sweep.py", line 89, in align_to_start_of_epoch
    start_idx, end_idx = sweep.epochs[epoch_name]
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by NileGraddis** [comment]
Hmm, so all analysis is failing because of a sweep with the following detected epoch indices:
```
{'test': (0, 1000), 'sweep': (0, 200999), 'recording': (0, 200999), 'experiment': None, 'stim': None}
```
(the others don't look so hot either):
```
{'test': (0, 1000), 'sweep': (0, 411999), 'recording': (0, 411999), 'experiment': (-14000, 426999), 'stim': (11000, 401999)}
```

These missing experiment epochs break align_to_start_of_epoch (presumably, the - epoch starts are also bad for downstream processing). It looks like the missing stim is real though - this sweep just has a test pulse - so the issue is that it is being selected by a [bare groupby on stimulus type](https://github.com/AllenInstitute/ipfx/blob/ce189e5642607d0548d168183d53a441d970483c/ipfx/data_set_features.py#L128)?

**Comment by NileGraddis** [comment]
lsq_analysis is failing because stim amplitude is always detected as 0:
```
    avg_rate        peak_deflect  stim_amp  v_baseline         sag     adapt  latency    isi_cv  mean_isi  median_isi  first_isi
6        1.0   (38.28125, 54364)       0.0  -68.629036  233.386063       NaN  0.81688       NaN       NaN         NaN        NaN
22      10.0       (37.0, 51975)       0.0  -67.296288  124.888107  0.108846  0.76908  0.382465  0.025391     0.03020    0.00474
21      10.0  (37.437504, 51985)       0.0  -67.495811   50.426174  0.105619  0.76928  0.412587  0.024696     0.02972    0.00492
20       6.0       (37.5, 52492)       0.0  -67.562462   68.023933  0.207982  0.77942  0.425952  0.040516     0.04984    0.00666
19       1.0   (37.65625, 54855)       0.0  -68.298920  110.168259       NaN  0.82668       NaN       NaN         NaN        NaN
18       1.0  (37.687504, 54590)       0.0  -68.477341  110.804329       NaN  0.82138       NaN       NaN         NaN        NaN
17       1.0  (37.687504, 54431)       0.0  -68.741432  298.961548       NaN  0.81820       NaN       NaN         NaN        NaN
23      10.0       (37.0, 51966)       0.0  -67.328560  155.527390  0.102824  0.76890  0.397034  0.025229     0.03004    0.00482
16       1.0   (37.90625, 55061)       0.0  -68.538528   71.890495       NaN  0.83078       NaN       NaN         NaN        NaN
12      13.0  (37.593754, 51714)       0.0  -67.410522  114.174782  0.071411  0.76386  0.356947  0.018457     0.02154    0.00430
11      12.0   (38.03125, 51791)       0.0  -67.118408   54.774937  0.085701  0.76540  0.361660  0.020191     0.02318    0.00434
10      10.0    (38.1875, 51981)       0.0  -67.500740  446.272675  0.109596  0.76920  0.420942  0.023393     0.02802    0.00462
9        8.0  (38.312504, 52180)       0.0  -67.894348  334.434479  0.160401  0.77320  0.461627  0.027686     0.03422    0.00496
8        7.0  (38.312504, 52430)       0.0  -67.619720  618.261536  0.187963  0.77818  0.472214  0.034853     0.04548    0.00574
7        4.0  (37.687504, 53108)       0.0  -68.720299  588.889954  0.405743  0.79176  0.587335  0.058033     0.07926    0.00994
13      15.0     (37.875, 51601)       0.0  -66.821106   33.573185  0.064435  0.76160  0.349421  0.016813     0.01896    0.00400
24      10.0  (36.812504, 51951)       0.0  -67.471062  143.473083  0.114088  0.76860  0.393471  0.025384     0.02956    0.00484
```

[This function](https://github.com/AllenInstitute/ipfx/blob/ce189e5642607d0548d168183d53a441d970483c/ipfx/stim_features.py#L39) is finding t index as `13500`, but all surrounding values are 0 ...

**Comment by NileGraddis** [comment]
![what_could_be_the_problem](https://user-images.githubusercontent.com/15089451/77782587-bebdfb80-7014-11ea-8460-3384af47c7d0.png)

**Comment by gouwens** [comment]
Could it be returning a different epoch than before? we've never had a stimulus start at 0.27. Right value is probably 1.02.

**Comment by NileGraddis** [comment]
@gouwens I agree. Examples should probably detect this automatically, but are currently hardcoded.

**Comment by gouwens** [comment]
Yeah, I think most of the examples are based on long-ago Friday Harbor workshop code.

**Comment by NileGraddis** [comment]
Here is the story of ramp analysis:
1. the voltage traces for these sweeps end in a bunch of zeros. `EphysDataSet` [nans these](https://github.com/AllenInstitute/ipfx/blob/ce189e5642607d0548d168183d53a441d970483c/ipfx/ephys_data_set.py#L265).
2. In order to get spikes for each sweep, `RampAnalysis` [calls on](https://github.com/AllenInstitute/ipfx/blob/ce189e5642607d0548d168183d53a441d970483c/ipfx/stimulus_protocol_analysis.py#L75) `SpikeFeatureExtractor.process`.
3. `SpikeFeatureExtractor.process` [calls on](https://github.com/AllenInstitute/ipfx/blob/ce189e5642607d0548d168183d53a441d970483c/ipfx/feature_extractor.py#L92) [`time_series_utils.calculate_dvdt`](https://github.com/AllenInstitute/ipfx/blob/ce189e5642607d0548d168183d53a441d970483c/ipfx/time_series_utils.py#L24)
4. `calculate_dvdt` attempts to [bessel filter the voltage traces](https://github.com/AllenInstitute/ipfx/blob/ce189e5642607d0548d168183d53a441d970483c/ipfx/time_series_utils.py#L45). This causes them to be all nan.
5. `calculate_dvdt` [removes all nans](https://github.com/AllenInstitute/ipfx/blob/ce189e5642607d0548d168183d53a441d970483c/ipfx/time_series_utils.py#L54) from the voltage trace. This kills the trace.
6. The spike detector [cannot find](https://github.com/AllenInstitute/ipfx/blob/ce189e5642607d0548d168183d53a441d970483c/ipfx/spike_detector.py#L51) any putative spikes in an empty array. The spike feature extractor [returns an empty dataframe](https://github.com/AllenInstitute/ipfx/blob/ce189e5642607d0548d168183d53a441d970483c/ipfx/feature_extractor.py#L103).
7. The `SpikeTrainFeatureExtractor` is now [called upon](https://github.com/AllenInstitute/ipfx/blob/ce189e5642607d0548d168183d53a441d970483c/ipfx/stimulus_protocol_analysis.py#L77) to extract features. It in turn [calls](https://github.com/AllenInstitute/ipfx/blob/ce189e5642607d0548d168183d53a441d970483c/ipfx/feature_extractor.py#L269) [`basic_spike_train_features`](https://github.com/AllenInstitute/ipfx/blob/ce189e5642607d0548d168183d53a441d970483c/ipfx/spike_train_features.py#L9).
8. but the spikes dataframe is empty, so `basic_spike_train_features` [returns a dictionary](https://github.com/AllenInstitute/ipfx/blob/ce189e5642607d0548d168183d53a441d970483c/ipfx/spike_train_features.py#L11) like `{"avg_rate": 0}`
9. Because no `latency` feature is calculated, `ramp_analysis.py` cannot plot it.

Some aspects of this process don't seem ideal to me.
1. `calculate_dvdt` should be able to handle trailing nans
2. `calculate_dvdt` should not just remove all nans from its output. Since dvdt is not intrinsically timestamped, only trailing nans are safe to remove. 
3. `detect_putative_spikes` does some runtime checking of voltage and time traces (types, equal lengths). Presumably an empty dvdt trace should also produce an error.

**Comment by gouwens** [comment]
@NileGraddis This might be a larger issue, but I think it stems from the decision to have some kind of value for truncated sweeps instead of just ending the sweep. It's been that way from the start (it used to be zeros, now it's NaNs) but it has always caused problems.

I'd argue that `calculate_dvdt` should be getting anything with NaNs, and more broadly, most sweeps shouldn't have NaNs as values throughout IPFX. The values at the "end of the trace" aren't missing - the cell or model never experienced them.

The reason `calculate_dvdt` removes NaNs at the point you linked is because it also accepts output from NEURON, which (during variable time step responses) sometimes returns multiple values at the same time point. That filtering eliminates those undefined points.

So, I think the real fix should be up in #1 of the story.

**Comment by NileGraddis** [comment]
@gouwens 

It sounds like the solution you are proposing is for the `EphysDataSet` to truncate i, t, and v when a sweep ends early. That seems pretty reasonable and safe to me (+ the tests pass locally with this change).

Can we handle the NEURON nans independently? Could you point me to how NEURON traces are passed to `calculate_dvdt`?

**Comment by NileGraddis** [comment]
It seems like the client code most likely to break with this change would be applications which try to stack sweeps into a rectangular array, or rely on a single sweep as representative of the others. I don't have a good sense for why this nan-ing behavior was implemented in the first place, though.

**Comment by gouwens** [comment]
@NileGraddis Yes, that's basically what I think should happen. Then we can just worry about if sweeps are long enough rather than finding intervals with "missing" data.

The switch to NaN happened because of #274 and the discussion therein. I realize I was the one who originally suggested NaNs as a substitute, but then ran into issues like #305. It seemed like selecting the "recording" epoch (or having that be the default) was a fix in that case, but we still have related issues cropping like here. Maybe the default changed with the EphysDataSet refactor?

**Comment by gouwens** [comment]
Sorry, forgot about pointing to where that's used with NEURON - here's an example:
https://github.com/AllenInstitute/biophys_optimize/blob/c6afcc03b706b341e22ceec612db228f11a1afec/biophys_optimize/utils.py#L146

The issue isn't that NEURON gives it NaNs, it's that there are points where two consecutive points have the same t, so you get a NaN in the dvdt. But probably a better filter would be
`    dvdt = dvdt[~(dt == 0)]
`

**Comment by NileGraddis** [comment]
well, these are building here: https://ipfx.readthedocs.io/en/384-fix-gallery/auto_examples/index.html

Looks like it is reporting them as broken if they don't have plots. Probably on account of the warnings.
