### ISSUE TITLE
Attach metadata should allow null genotype

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ipfx#407]
All attach metadata jobs for human fail because they do not have genotype data.  We should enforce this requirement for mice elsewhere.  Need to change this to allow null genotype.

Example log file:
/allen/programs/celltypes/production/humancelltypes/prod125/Ephys_Roi_Result_769228073/EPHYS_ATTACH_METADATA_QUEUE_1017273377/202004272155_EPHYS_ATTACH_METADATA_QUEUE_769228073.log

marshmallow.exceptions.ValidationError: {'metadata': {6: {'value': ['Field may not be null.']}}}

This change should probably be to the upstream LIMS strategy instead:  Make it return blank instead of null if there really is no donor.full_genotype.

e.g.

```
    {
      "name": "genotype",
      "value": "",
      "sinks": [
        "dandi_yaml"
      ]
    },
```

**Comment by NileGraddis** [comment]
http://jira.corp.alleninstitute.org/browse/PBS-2287
