### ISSUE TITLE
Update sweep qc tool to use released ipfx

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ipfx#415]
update sweep qc requirements to point to the new ipfx so that MPE can pull down a new version of sweep qc tool that uses the new ipfx
Make new release of sweep qc tool.
Run tests to make sure it works.

**Comment by NileGraddis** [comment]
This is working pointing at dev. Here is an issue to change the line in requirements when ipfx is actaully posted to pypi:
https://github.com/AllenInstitute/sweep_qc_tool/issues/65
