### ISSUE TITLE
Feature extractor module runs jobs for nwb1 files that are no longer supported by ipfx

### ISSUE THREAD

**Issue by sgratiy** [AllenInstitute/ipfx#452]
**Describe the bug**
File "/allen/aibs/technology/conda/production/fx/lib/python3.6/site-packages/ipfx/dataset/create.py", line 118, in create_ephys_data_set
nwb_version["major"], nwb_version["full"]
ValueError: Unsupported or unknown NWB major version 1 (NWB-1.0.5)

**To Reproduce**
check recent failed jobs on EPHYS_FEATURE_EXTRACTION_V3_QUEUE

**Comment by NileGraddis** [comment]
The ephys pipeline strategies have logic like this:
- http://stash.corp.alleninstitute.org/projects/TECH/repos/lims/browse/app/strategies/ephys_nwb_stimulus_summary_v3_strategy.rb#46
- http://stash.corp.alleninstitute.org/projects/TECH/repos/lims/browse/app/strategies/ephys_feature_extraction_v3_strategy.rb#44

which gets the appropriate input NWB file. Problem: they only select from a list of well known file types that represent old, NWB1 files, while ipfx only supports up-to-date MIES NWB2s. Files that have been grandfathered in are stored as `EphysNWB2`, but new uploads do not create records of this type.

It seems like we need to do the following:
- [ ] update `EphysNwbStimulusSummaryV3Strategy` to accept/expect only `EphysNWB2`
- [ ] update `EphysFeatureExtractionV3Strategy` to accept/expect only `EphysNWB2`
- [ ] update [`EphysTriggerKeyValidator`](http://stash.corp.alleninstitute.org/projects/TECH/repos/lims/browse/app/models/ephys_trigger_key_validator.rb)'s key -> well known file type map to have an entry for EphysNWB2
- [ ] tell MPE (or whoever writes the trigger file) that they need a new key
- [ ] update [`EphysSpecimenRoiPlanStrategy`](http://stash.corp.alleninstitute.org/projects/TECH/repos/lims/browse/app/strategies/ephys_specimen_roi_plan_strategy.rb) to create `EphysNWB2` records.

The first and second items are blockers for #451 - we can't test run current ipfx in LIMS unless LIMS is able to supply the NWB version required by current ipfx.

**Comment by NileGraddis** [comment]
jira: http://jira.corp.alleninstitute.org/browse/PBS-2344

**Comment by NileGraddis** [comment]
Feature extractor fails if it is provided an NWB2 file with spikes, but `EphysNWB2` records may be spiked or unspiked files. We need to:

[ ] - create an `EphysNWB2Spikes` (or something) well known file type
[ ] - update feature extractor to output `EphysNWB2Spikes`
[ ] - update attach metadata to input `EphysNWB2Spikes`
[ ] - identify the sets of roi results whose `EphysNWB2` records (a) do not have or (b) have spikes
[ ] - swap the well known file type of each file attached to an roi in (b) to `EphysNWB2Spikes`
[ ] - for each roi in (b), locate its spikeless MIES NWB2 file, and upload that file as an `EphysNWB2` record
[ ] run the rois in (a) through the pipeline

Wayne has provided criteria which can be used to find which `EphysNWB2` records have or do not have spikes:
```
In general, any "EphysNWB2" file whose attached EphysRoiResult has published_at IN ('2020-07-11','2020-07-12'), should have spikes.
An "EphysNWB2" file whose attached EphysRoiResult has published_at IS NULL or is not one of those two July 2020 dates, should NOT have spikes
```
