### ISSUE TITLE
qc_figs_dir should be relative to the cell output directory

### ISSUE THREAD

**Issue by sgratiy** [AllenInstitute/ipfx#454]
**Describe the bug**
qc_figs_dir should be always included inside the cell output dir rather then being an arbitrary output path because otherwise user would not be able to relate figure generated to the cell output folder. Also, this makes a more organized output and avoids a need to create an empty qc_figs_dir. The input.json should include the path to the qc_figs_dir

**Desired behavior**
instead of `qc_fig_dir`  add `plot_figures` parameter with the default True. It will create a directory in an expected location inside the cell folder and add it to the input.json.

**Comment by NileGraddis** [comment]
@sgratiy [LIMS argues](http://stash.corp.alleninstitute.org/projects/TECH/repos/lims/browse/app/strategies/ephys_feature_extraction_v3_strategy.rb#55,18,20) qc_fig_dir as a full path to run_feature_extraction. The LIMS change to stop doing this would be pretty minor, though other users might be broken by the removal of qc_fig_dir. Maybe we can avoid breaking changes entirely though. Why not:
1. make qc_fig_dir default to a subdirectory of the outputs
2. add a plot_qc_figures parameter that controls whether figures are generated.

The upside: no breaking changes, and we support (probably rare) users who really want to organize their outputs differently. The downside: a bit more complication for a pretty niche case (that happens to be implemented in LIMS). What do you think @sgratiy @wbwakeman ?

**Comment by sgratiy** [comment]
@NileGraddis, I agree on avoiding breaking changes in LIMS - this is how I envisioned when describing the issue. I have not argued to remove qc_fig_dir from the input.json
In fact, I would not let users to specify an arbitrary location for the qc_fig_dir.
I would use an optional `plot_figures` command line argument instead that would construct the path.

**Comment by NileGraddis** [comment]
I don't think I understand your proposed solution. Are you saying that we still have qc_fig_dir, but reject paths that are not inside the output directory or ignore it entirely?

**Comment by sgratiy** [comment]
Users should have a command line argument like `plot_qc_figures` for the run_pipeline_from_nwb_file. If `plot_qc_figures`=True, then qc_fig_dir is constructed to a subdir of the outputs. If `plot_qc_figures`=False, then qc_fig_dir=None. Makes sense?

**Comment by NileGraddis** [comment]
What happens if a user provides both qc_fig_dir and plot_qc_figures? Does the behavior depend on where the specified qc_fig_dir is? Can a user even supply their own_qc_fig_dir at all?
