### ISSUE TITLE
Deploy ipfx 1.0.0 to production environment

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ipfx#459]
Update production conda environment with the 1.0.0 release of ipfx

Acceptance criteria:
- [x] running the following returns '1.0.0'
```
conda activate /allen/aibs/technology/conda/production/fx
conda list | grep ipfx
```

**Comment by gnayuy** [comment]
http://bamboo.corp.alleninstitute.org/deploy/viewDeploymentProjectEnvironments.action?id=164855841

release-20 with ipfx version 1.0.0 is deployed to /allen/aibs/technology/conda/production/fx
