### ISSUE TITLE
Implement fix on LIMS strategy to get correct ontology

### ISSUE THREAD

**Issue by isaak-willett** [AllenInstitute/ipfx#476]
@sgratiy found during his investigation of #469 that the ontology provided by LIMS strategy are not congruent with the ontology provided by python library. The LIMS strategy needs to be updated to give the correct ontology.

### Tasks:
- Implement fix in the `get_code_tag_for_stimulus` function in the `ephys_nwb_stimulus_summary_v3_strategy.rb`, can be found at this link, [lims repo](http://stash.corp.alleninstitute.org/projects/TECH/repos/lims/browse/app/strategies/ephys_nwb_stimulus_summary_v3_strategy.rb#33)

### Validation Criteria:
- [ ] Can run a lims job through to completion on a dev lims build and produce results without nulls for long squares in the lims output json, see the original issue #469

**Comment by wbwakeman** [comment]
Get Wayne to help with the LIMS parts - just identify the strategy changes needed
