### ISSUE TITLE
Fix Truncated Pulse Error

### ISSUE THREAD

**Issue by ozsat** [AllenInstitute/ipfx#485]
If the test pulse is truncated then in the `qc_feature.py` `get_square_pulse_idx` the program will stop. We would like to handle square pulses which contain truncated pulse. As a solution, we would like to skip the truncated pulse if it is presented in the square pulses. 
We worked on this issue since a couple of our recordings contained truncated pulses. We developed a simple solution to this problem, and we will share it soon.

**Comment by tmchartrand** [comment]
Chose not to fix this but edit the files in question instead, adding a single baseline data point at the beginning of sweeps preceding the test pulse.
