### ISSUE TITLE
Update ipfx bamboo builds for new server

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ipfx#487]
The `axon` and `bouton` servers are going away by Thanksgiving.  Need to do something with the Bamboo agents on those servers for the following builds:

bouton:
IFR-IG                ipfx (GitHub)
IFR-AIN              ipfx nightly              (recent)

axon:
IFR-IG                ipfx (GitHub)
IFR-AIN              ipfx nightly (recent)

New server is `synapse`.

**Comment by sgratiy** [comment]
Fix the build by updating plan requirements and corresponding plan capabilities
http://bamboo.corp.alleninstitute.org/browse/IFR-IG95-5
