### ISSUE TITLE
citation?

### ISSUE THREAD

**Issue by bendichter** [AllenInstitute/ipfx#489]
What is the best way to cite this software?

**Comment by wbwakeman** [comment]
Here is some information on how to cite this resource, based on https://alleninstitute.org/legal/citation-policy/

© [[year of first publication]] Allen Institute for Brain Science. [Name of Allen Institute Resource]. Available from: [Resource URL]

Example:
© 2020 Allen Institute for Brain Science. Intrinsic Physiology Feature Extractor (IPFX). Available from: github.com/AllenInstitute/ipfx

**Comment by bendichter** [comment]
Thanks, @wbwakeman!
