### ISSUE TITLE
Triage ipfx issues

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ipfx#517]
We need to get a handle of recent ipfx issues that are preventing data from being processed through the internal pipeline.  Rusty has entered some issues recently, including some PRs, that need to be reviewed so that we can scope out well-defined pieces of work for this team.  This issue is to review those issues, ask for additional information as needed, and gain the background needed so that these issues can be discussed and scoped with the Marmot team.

Timeboxed to 2 days.

#509 Rusty's file updates https://github.com/AllenInstitute/ipfx/issues/509#issuecomment-825027099
#515 IndexError: Cannot find ('EXTPCllATT',)
#516 Failed and dropped sweeps are being used in Feature Extraction

#508/PR511 Sweeps with tags must be included in sweep_states
#513/PR514 extract electrode_0 should check pipette resistance before
#507 Sweeps that fail qc are incorrectly recorded in LIMS with the state "auto passed"
#499 add ability to set specific sweep checks as optional

Validation criteria:
- [x] Issues are written so that Marmot team believes them to be well-defined with actionable pieces of work

**Comment by sgratiy** [comment]
#509 Rusty's file update: Added comment with the tasks
#515 IndexError: Cannot find ('EXTPCllATT',): Should be fixed automatically with #509
#516 Failed and dropped sweeps are being used in Feature Extraction:  Investigating into LIMS strategy...

#508/PR511 Sweeps with tags must be included in sweep_states: Reviewed PR. Fix works with minor suggestion. General solution needed for future.
#513/PR514 extract electrode_0 should check pipette resistance before
#507 Sweeps that fail qc are incorrectly recorded in LIMS with the state "auto passed"
#499 add ability to set specific sweep checks as optional
