### ISSUE TITLE
Can't pip install (dependency conflicts with AllenSDK?)

### ISSUE THREAD

**Issue by tmchartrand** [AllenInstitute/ipfx#550]
I'm not sure if this is universal, but currently a direct pip install of IPFX fails in a fresh python 3.8 conda environment. As far as I can tell, some dependency conflicts are forcing it back to an older AllenSDK version, which then requires an older version of tables (3.5.1) which has some install issues.

I'm guessing there are some requirements on both sides that could be loosened, but ultimately the best solution is probably to eliminate dependency on AllenSDK by breaking out the core modules that are actually used by other packages like IPFX. I've filed an issue there for that: https://github.com/AllenInstitute/AllenSDK/issues/2585.

**Comment by guoyanzhao** [comment]
I was trying to install IPFX using recommended "pip install ipfx" but it failed. Lots of dependency issues. Could you please export your environment configuration so that other people can use that to create a conda enviroment that works?

**Comment by sheriferson** [comment]
The PR to update IPFX Python version support and update most dependencies has been merged. This should resolve the installation issues you're facing if you install from the master branch. That said, the version hasn't been published to PyPI yet.

**Comment by sheriferson** [comment]
IPFX 2.0.0 is now on PyPI and supports Python 3.9 to 3.11.

I think this should resolve the issues you are seeing @tmchartrand and @guoyanzhao. I will close this issue, but please reopen if there are still issues.
