### ISSUE TITLE
 ERROR collecting tests/test_x_nwb_helper.py

### ISSUE THREAD

**Issue by sgratiy** [AllenInstitute/ipfx#95]
16-Oct-2018 22:00:37 | collecting 51 items / 2 errors
-- | --
16-Oct-2018 22:00:37 | collected 51 items / 2 errors
16-Oct-2018 22:00:37 |  
16-Oct-2018 22:00:37 | ==================================== ERRORS ====================================
16-Oct-2018 22:00:37 | _____________________ ERROR collecting tests/test_x_nwb.py _____________________
16-Oct-2018 22:00:37 | /opt/conda/envs/py27/lib/python2.7/site-packages/_pytest/python.py:412: in _importtestmodule
16-Oct-2018 22:00:37 | mod = self.fspath.pyimport(ensuresyspath=importmode)
16-Oct-2018 22:00:37 | /opt/conda/envs/py27/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
16-Oct-2018 22:00:37 | __import__(modname)
16-Oct-2018 22:00:37 | E     File "/root/ipfx/tests/test_x_nwb.py", line 48
16-Oct-2018 22:00:37 | E       folder = f"reference_{ext}"
16-Oct-2018 22:00:37 | E                                 ^
16-Oct-2018 22:00:37 | E   SyntaxError: invalid syntax
16-Oct-2018 22:00:37 | _________________ ERROR collecting tests/test_x_nwb_helper.py __________________
16-Oct-2018 22:00:37 | /opt/conda/envs/py27/lib/python2.7/site-packages/_pytest/python.py:412: in _importtestmodule
16-Oct-2018 22:00:37 | mod = self.fspath.pyimport(ensuresyspath=importmode)
16-Oct-2018 22:00:37 | /opt/conda/envs/py27/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
16-Oct-2018 22:00:37 | __import__(modname)
16-Oct-2018 22:00:37 | E     File "/root/ipfx/tests/test_x_nwb_helper.py", line 88
16-Oct-2018 22:00:37 | E       print(f"Download large file {filename}, please be patient.")
16-Oct-2018 22:00:37 | E                                                                 ^
16-Oct-2018 22:00:37 | E   SyntaxError: invalid syntax
16-Oct-2018 22:00:37 | ------------- generated xml file: /root/ipfx/test-reports/test.xml -------------
16-Oct-2018 22:00:37 | !!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
16-Oct-2018 22:00:37 | =========================== 2 error in 2.83 seconds ============================

**Comment by t-b** [comment]
@sgratiy You need python 3.6 or later for all code related to the conversion scripts.

**Comment by t-b** [comment]
@sgratiy Anything more I can do here?

**Comment by sgratiy** [comment]
@t-b I am not sure how this could work considering that my code is in python 2.7.

**Comment by sgratiy** [comment]
For now I am skipping py3 tests when running on py2

**Comment by t-b** [comment]
Closing in favour of #141.
